#!/bin/sh
# The File Alteration Monitor daemon
#
# (cloux@rote.ch)
exec 2>&1

DAEMON="$(command -v famd)"
[ -x "$DAEMON" ] || exit
FAMOPTS="-T 0"
[ -r ./conf ] && . ./conf

# Make sure the rpcbind is running
svactivate rpcbind >/dev/null || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# kill unsupervised instance
pkill -f "$DAEMON"

exec "$DAEMON" -f $FAMOPTS 2>&1
