#!/bin/sh
#
# Write an empty record for tty to the wtmp file
# to indicate that the user on the terminal has logged out
# (jan@wespe.dev)

tty=${PWD##*-}
[ $(expr "$tty" : '^[0-9]*$') -gt 0 ] && tty=tty${tty}
[ -c /dev/"$tty" ] || tty=tty1
exec utmpset -w $tty
