#!/bin/sh
# glances - An eye on your system
#
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON="$(command -v $NAME)"
[ -x "$DAEMON" ] || exit

USER=$NAME
CONF="/etc/glances/glances.conf"
[ -f ./conf ] && . ./conf
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
DAEMON_ARGS="-C $CONF -s -B 127.0.0.1"

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec chpst -u $NAME "$DAEMON" $DAEMON_ARGS 2>&1
