#!/bin/sh
#
# Runit stage 2: start services in parallel and keep them alive
# based on VOID Linux (https://www.voidlinux.org)

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /etc/runit/functions
msg "Entering Runit stage 2 ($0)"

# runlevel kernel parameter support
RUNLEVEL=default
KERNEL_ARG=$(grep -o 'runlevel=[^ ]*' /proc/cmdline | grep -o '[^=]*$')
if [ "$KERNEL_ARG" ]; then
	msg "Runlevel detected: '$KERNEL_ARG' (via kernel cmdline)"
	RUNLEVEL="$KERNEL_ARG"
fi
if [ -d /etc/runit/runsvdir/$RUNLEVEL ]; then
	runsvchdir $RUNLEVEL >/dev/null
else
	msg "WARNING: Runlevel '$RUNLEVEL' does not exist!"
fi

# execute rc.local for sysvinit compatibility
[ -x /etc/rc.local ] && /etc/rc.local

exec env - PATH=$PATH \
runsvdir -P /etc/service 'log: ...................................................................................'
