#!/bin/sh
#
# Runit stage 2: start services in parallel and keep them alive
# based on VOID Linux (https://www.voidlinux.org)

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

printf '=> Entering Runit stage 2 (%s)\n' "$0"

# runlevel kernel parameter support
RUNLEVEL=default
KERNEL_ARG=$(grep -o 'runlevel=[^ ]*' /proc/cmdline | grep -o '[^=]*$')
if [ "$KERNEL_ARG" ]; then
	printf '=> Runlevel detected: %s (via kernel cmdline)\n' "$KERNEL_ARG"
	RUNLEVEL="$KERNEL_ARG"
fi
if [ -d /etc/runit/runsvdir/$RUNLEVEL ]; then
	runsvchdir $RUNLEVEL >/dev/null
else
	printf '=> WARNING: Runlevel %s does not exist!\n' "$RUNLEVEL"
fi

# execute rc.local for sysvinit compatibility
[ -x /etc/rc.local ] && /etc/rc.local

exec env - PATH=$PATH \
runsvdir -P /etc/service 'log: ...................................................................................'
