#!/bin/sh
# Start default X11 display manager
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}

# quit if boot requires text mode
if grep -wqs text /proc/cmdline; then
	printf 'Not starting display manager, found "text" in kernel commandline.\n'
	sv stop "$NAME" >/dev/null
	exit
fi

# read defaults
DEFAULT_DISPLAY_MANAGER=''
[ -r ./conf ] && . ./conf
[ -r /etc/default/X11dm ] && . /etc/default/X11dm

# find the X11 display manager
if [ ! -x "$DEFAULT_DISPLAY_MANAGER" ]; then
	[ -r "$DEFAULT_DISPLAY_MANAGER_FILE" ] || DEFAULT_DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager
	[ -r "$DEFAULT_DISPLAY_MANAGER_FILE" ] || DEFAULT_DISPLAY_MANAGER_FILE=/etc/sysconfig/displaymanager
	[ -r "$DEFAULT_DISPLAY_MANAGER_FILE" ] || DEFAULT_DISPLAY_MANAGER_FILE=/etc/sysconfig/desktop
	if [ ! -r "$DEFAULT_DISPLAY_MANAGER_FILE" ]; then
		printf 'ERROR: %s display manager could not be determined.\n' "$NAME"
		sv stop "$NAME" >/dev/null
		exit
	fi
	DEFAULT_DISPLAY_MANAGER="$(head -n 1 "$DEFAULT_DISPLAY_MANAGER_FILE")"
	if [ ! -x "$DEFAULT_DISPLAY_MANAGER" ]; then
		printf 'ERROR: display manager "%s" can not be executed.\n' "$DEFAULT_DISPLAY_MANAGER"
		sv stop "$NAME" >/dev/null
		exit
	fi
fi

# make sure the login manager is up, stop X11 on elogind timeout
ELOGIND="$(sv start elogind)"
printf '%s' "$ELOGIND" | grep -q '^timeout:' && sv stop "$NAME" && exit
printf '%s' "$ELOGIND" | grep -q '^ok: *run:' || exit

# export locale
[ -r /etc/default/locale ] && . /etc/default/locale
export LANG LANGUAGE

exec "$DEFAULT_DISPLAY_MANAGER"
