#!/bin/sh
# inetd - internet superserver
# (cloux@rote.ch)
exec 2>&1

DAEMON="$(command -v inetd)"
[ -x "$DAEMON" ] || exit
[ -r /etc/default/openbsd-inetd ] && . /etc/default/openbsd-inetd

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec "$DAEMON" -i $OPTIONS
