#!/bin/sh -e
#
# man-db cron daily

# Skip in favour of systemd timer.
[ -d /run/systemd/system ] && exit 0

# run only if can be started nicely
[ "$(command -v ionice)" ] || exit 1

iosched=0
# Don't try to change I/O priority in a vserver or OpenVZ.
if ! egrep -q '(envID|VxID):.*[1-9]' /proc/self/status && \
   ([ ! -d /proc/vz ] || [ -d /proc/bc ]); then
    iosched=3
fi

# Recover from deletion, per FHS.
if ! [ -d /var/cache/man ]; then
  install -d -o man -g man -m 0755 /var/cache/man
fi

# expunge old catman pages which have not been read in a week
ionice --class $iosched --ignore find /var/cache/man -type f -name '*.gz' \
-atime +6 -delete >/dev/null 2>/dev/null

# NOTE: do not start as a daemon, for compatibility with other-than-sysvinit init systems
# regenerate man database
[ -x /usr/bin/mandb ] &&
  ionice --class $iosched --ignore /usr/bin/mandb --quiet 2>/dev/null
