#!/bin/sh

# load config files
[ -r ./conf ] && . ./conf
[ -r /etc/default/auditd ] && . /etc/default/auditd

rm -f /var/run/audit_events

if ! printf '%s' "$AUDITD_CLEAN_STOP" | grep -i 'no'; then
  [ -f /etc/audit/audit-stop.rules ] && /sbin/auditctl -R /etc/audit/audit-stop.rules >/dev/null
fi
