#!/bin/sh
# auditd - The Linux Audit daemon
exec 2>&1

NAME=${PWD##*/}
DAEMON="$(command -v $NAME)"
[ -x "$DAEMON" ] || exit
[ -r ./conf ] && . ./conf
[ -r /etc/default/"$NAME" ] && . /etc/default/"$NAME"

if ! printf '%s' "$USE_AUGENRULES" | grep -iq 'no'; then
  [ -d /etc/audit/rules.d ] && /sbin/augenrules >/dev/null
fi
[ -f /etc/audit/audit.rules ] && /sbin/auditctl -R /etc/audit/audit.rules >/dev/null

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec /sbin/auditd -f -n $EXTRAOPTIONS
