#!/bin/sh
# UUID generation daemon
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit

UUIDD_USER=uuidd
UUIDD_GROUP=uuidd
UUIDD_DIR=/run/uuidd
[ -r ./conf ] && . ./conf
[ -d "$UUIDD_DIR" ] || install -o "$UUIDD_USER" -g "$UUIDD_GROUP" -d "$UUIDD_DIR"

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec "$DAEMON" --no-fork --no-pid --quiet 2>/dev/null
