#!/bin/sh
# Dropbear - Lightweight SSH server
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v "$NAME")
[ -x "$DAEMON" ] || exit

DROPBEAR_PORT=22
DROPBEAR_RECEIVE_WINDOW=65536
DROPBEAR_EXTRA_ARGS=
DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"
DROPBEAR_DSSKEY="/etc/dropbear/dropbear_dss_host_key"
DROPBEAR_ECDSAKEY="/etc/dropbear/dropbear_ecdsa_host_key"
DROPBEAR_ED25519KEY="/etc/dropbear/dropbear_ed25519_host_key"

[ -f /etc/default/dropbear ] && . /etc/default/dropbear
[ -f ./conf ] && . ./conf
[ -f "$DROPBEAR_BANNER" ] && DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -b $DROPBEAR_BANNER"
[ -f "$DROPBEAR_RSAKEY" ] && DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -r $DROPBEAR_RSAKEY"
[ -f "$DROPBEAR_DSSKEY" ] && DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -r $DROPBEAR_DSSKEY"
[ -f "$DROPBEAR_ECDSAKEY" ] && DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -r $DROPBEAR_ECDSAKEY"
[ -f "$DROPBEAR_ED25519KEY" ] && DROPBEAR_EXTRA_ARGS="$DROPBEAR_EXTRA_ARGS -r $DROPBEAR_ED25519KEY"

exec $DAEMON -FEg -p $DROPBEAR_PORT -W $DROPBEAR_RECEIVE_WINDOW $DROPBEAR_EXTRA_ARGS 2>&1
