#!/bin/sh
# RPCSEC_GSS daemon - provide strong security for NFS
# Activated automatically from rpcbind
# (cloux@rote.ch)
exec 2>&1

NAME=rpc.gssd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

KEYTAB=/etc/krb5.keytab
[ -f ./conf ] && . ./conf

# Ensure that the RPC pipefs is available
PIPEFS_PATH="$(findmnt -n -t rpc_pipefs -o target 2>/dev/null)"
if [ -z "$PIPEFS_PATH" ]; then
	printf 'ERROR: rpc.gssd requires rpc_pipefs to be mounted.\n'
	exit 1
fi


# Terminate unsupervised instance
pkill -f "$DAEMON"

# Run daemon
exec "$DAEMON" -f -k "$KEYTAB" -p "$PIPEFS_PATH"
