#!/bin/sh
# DNS server
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# fix supervise symlink
[ -h ./supervise ] && rm ./supervise && mkdir -m 700 supervise

# set defaults
[ -f ./conf/DATALIMIT ] && DATASEGMENT="-d $(grep -m 1 '[0-9]*' ./conf/DATALIMIT)"
export IP=127.0.0.1
export ROOT=${PWD}/root

# run
exec chpst -e ./conf -U tinydns $DATASEGMENT $DAEMON
