#!/bin/sh
# DNS server
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# fix supervise symlink
[ -h ./supervise ] && rm ./supervise && mkdir -m 700 supervise

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# limit data segment
[ -f ./conf/DATALIMIT ] && DATASEGMENT="-d $(grep -m 1 '[0-9]*' ./conf/DATALIMIT)"

# run
exec chpst -e ./conf -U tinydns $DATASEGMENT $DAEMON
