#!/bin/sh
# LVM poll daemon
# (cloux@rote.ch)
exec 2>&1

NAME=lvmpolld
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# stop any unsupervised daemons
killall --quiet --exact "$NAME"

[ -d /run/lvm ] || mkdir -m 0700 /run/lvm

exec "$DAEMON" -f -l wire >/dev/null 2>/dev/null
