#!/bin/sh
# LVM metadata cache daemon
# (jan@wespe.dev)
exec 2>&1

NAME=lvmetad
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# stop any unsupervised daemons
pkill -f "$DAEMON"

exec "$DAEMON" -f -l error >/dev/null 2>/dev/null
