#!/bin/sh
# Name Service Cache Daemon
#
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON="$(command -v $NAME)"
[ -x "$DAEMON" ] || exit

THREADS=$(nproc)
CONFIG_FILE="/etc/nscd.conf"
[ -r ./conf ] && . ./conf
mkdir /run/nscd 2>/dev/null

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

"$DAEMON" --shutdown
exec "$DAEMON" -F -f "$CONFIG_FILE" -t $THREADS 2>/dev/null
