#!/bin/sh
# udev/eudev dynamic device manager
# (cloux@rote.ch)
exec 2>&1

DAEMON="/sbin/udevd"
[ -x "$DAEMON" ] || exit

# udevd could be started unsupervised in the early init.
# kill the old daemon first
/sbin/udevadm control --exit 2>/dev/null

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec $DAEMON 2>/dev/null
