#!/bin/sh
# firewalld - Dynamic Firewall Manager
# (jan@wespe.dev)
exec 2>&1

DAEMON="$(command -v firewalld)"
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# kill unsupervised instance
pkill -f "$DAEMON"

exec "$DAEMON" --nofork --nopid 2>&1
