#!/bin/sh
# NFSv4 kernel client and server ID <-> Name Mapper
#
# Activated automatically from rpcbind
# NOTE: on more recent kernels only the NFSv4 server uses rpc.idmapd,
# the client uses nfsidmap instead, and only falls back to rpc.idmapd
# if there was a problem running the nfsidmap program.
#
# (jan@wespe.dev)
exec 2>&1

NAME=rpc.idmapd
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Ensure that the RPC pipefs is available
PIPEFS_PATH="$(findmnt -n -t rpc_pipefs -o target 2>/dev/null)"
if [ -z "$PIPEFS_PATH" ]; then
	printf 'ERROR: rpc.idmapd requires rpc_pipefs to be mounted.\n'
	exit 1
fi

# Terminate unsupervised instance
pkill -f "$DAEMON"

# Run daemon
exec "$DAEMON" -f -p "$PIPEFS_PATH"
