#!/bin/sh
# Wicd Network Manager
# (jan@wespe.dev)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

# Load config
DAEMON_ARGS="--keep-connection"
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
[ -r ./conf ] && . ./conf
[ "$START_DAEMON" = "no" ] && exit

# Wait for DBus
sv start dbus >/dev/null || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

rm -f /run/wicd/wicd.pid
exec "$DAEMON" --no-daemon $DAEMON_ARGS >/dev/null 2>/dev/null
