#!/bin/sh
#
# Start firewall
# (jan@wespe.dev)

[ -x /usr/sbin/firehol ] || exit
set -a
[ -f /etc/default/firehol ] && . /etc/default/firehol
printf '%s' "$START_FIREHOL" | grep -q 'YES' || exit

# firehol requires iptables-legacy, see
# https://github.com/netblue30/firejail/issues/2232#issuecomment-436423748 
update-alternatives --set iptables /usr/sbin/iptables-legacy >/dev/null 2>/dev/null

# note: redirect to /dev/null disables color codes
/usr/sbin/firehol start >/dev/null
