#!/bin/sh
#
# Integrate runit-init system functions
# (cloux@rote.ch)
#

# apply compatibility scripts for runit
# use symlinks for easy transition between different init systems
#
# NOTE: this will invalidate updates from the repository,
# since package manager expects the original file instead of symlinks
for COMPAT in insserv runlevel shutdown; do
	if [ ! -L /sbin/$COMPAT ] && [ -x /sbin/$COMPAT.runit ]; then
		mv -f /sbin/$COMPAT /sbin/$COMPAT.sysv
		ln -sv $COMPAT.runit /sbin/$COMPAT
	fi
done
for COMPAT in update-rc.d; do
	if [ ! -L /usr/sbin/$COMPAT ] && [ -x /usr/sbin/$COMPAT.runit ]; then
		mv -f /usr/sbin/$COMPAT /usr/sbin/$COMPAT.sysv
		ln -sv $COMPAT.runit /usr/sbin/$COMPAT
	fi
done

# apply power control compatibility symlinks
for COMPAT in halt poweroff; do
	if [ "$(readlink -n /sbin/$COMPAT)" != "shutdown" ]; then
		mv -vf /sbin/$COMPAT /sbin/$COMPAT.sysv
		ln -sfv shutdown /sbin/$COMPAT
	fi
done
if [ -x /etc/runit/ctrlaltdel ]; then
	for COMPAT in ctrlaltdel reboot; do
		if [ "$(readlink -n /sbin/$COMPAT)" != "/etc/runit/ctrlaltdel" ]; then
			mv -vf /sbin/$COMPAT /sbin/$COMPAT.sysv
			ln -sfv /etc/runit/ctrlaltdel /sbin/$COMPAT
		fi
	done
fi

# If only runit-init and no other init is being used,
# this autorun script can be disabled:
#chmod 644 "$0"
