#!/bin/sh
#
# Integrate runit system commands
# rename original files to *.sysv
#
# (cloux@rote.ch)
#

apply_runit_cmd() {
	for CMD in $@; do
		[ -x "$CMDPATH/$CMD.runit" ] || continue
		if [ "$(readlink -n "$CMDPATH/$CMD")" != "$CMD.runit" ]; then
			[ -e "$CMDPATH/$CMD" ] && mv -f "$CMDPATH/$CMD" "$CMDPATH/$CMD".sysv
			ln -sfv "$CMD.runit" "$CMDPATH/$CMD"
		fi
	done
}
CMDPATH=/sbin
apply_runit_cmd insserv runlevel shutdown

CMDPATH=/usr/sbin
apply_runit_cmd invoke-rc.d start-statd update-rc.d

CMDPATH=/bin
apply_runit_cmd pidof

# apply power control symlinks
for CMD in halt poweroff; do
	if [ "$(readlink -n /sbin/$CMD)" != "shutdown" ]; then
		mv -f /sbin/$CMD /sbin/$CMD.sysv 2>/dev/null
		ln -sfv shutdown /sbin/$CMD
	fi
done
for CMD in ctrlaltdel reboot; do
	if [ "$(readlink -n /sbin/$CMD)" != "/etc/runit/ctrlaltdel" ]; then
		mv -f /sbin/$CMD /sbin/$CMD.sysv 2>/dev/null
		ln -sfv /etc/runit/ctrlaltdel /sbin/$CMD
	fi
done
