#!/bin/sh
#
# VirtualBox host and guest support
#

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# VirtualBox Host
[ -x /etc/init.d/vboxdrv ] && /etc/init.d/vboxdrv start

# VirtualBox Guest Additions
[ -x /etc/init.d/vboxadd ] && /etc/init.d/vboxadd start
