#!/bin/sh
#
# SANE network scanner server
# (jan@wespe.dev)
exec 2>&1

NAME=${PWD##*/}
DAEMON="$(command -v $NAME)"
[ -x "$DAEMON" ] || exit

# config variables
RUN_AS_USER=saned
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# stop other daemons
pkill "$NAME"

exec "$DAEMON" -l -u "$RUN_AS_USER" >/dev/null 2>/dev/null
