#!/bin/sh
# OOMD - Out Of Memory killer Daemon
# https://github.com/facebookincubator/oomd
#
# (jan@wespe.dev)
exec 2>&1

DAEMON=$(command -v oomd)
[ "$DAEMON" ] || DAEMON=$(command -v oomd_bin)
[ -x "$DAEMON" ] || exit

CONFIG=/etc/oomd.json
[ -f "$CONFIG" ] || CONFIG=/etc/oomd/oomd.json
[ -f "$CONFIG" ] || CONFIG=/usr/local/etc/oomd/oomd.json
[ -f "$CONFIG" ] || exit

exec "$DAEMON" --config "$CONFIG" 2>&1
