#!/bin/sh
# OOMD - Out Of Memory killer Daemon
# https://github.com/facebookincubator/oomd
#
# (cloux@rote.ch)
exec 2>&1

DAEMON=$(command -v oomd)
[ "$DAEMON" ] || DAEMON=$(command -v oomd_bin)
[ -x "$DAEMON" ] || exit

exec "$DAEMON" 2>&1
