#!/bin/sh
# kxd - Key exchange daemon
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON=$(command -v $NAME)
[ -x "$DAEMON" ] || exit

[ -r ./conf ] && . ./conf
[ -r /etc/default/$NAME ] && . /etc/default/$NAME
DAEMON_ARGS="$DAEMON_ARGS --logfile=-"

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec $DAEMON $DAEMON_ARGS 2>/dev/null
