#!/bin/sh
#
# Libvirt logging daemon
# (cloux@rote.ch)
exec 2>&1

NAME=${PWD##*/}
DAEMON="$(command -v $NAME)"
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# Include virtlogd defaults if available
[ -f /etc/default/virtlogd ] && . /etc/default/virtlogd

exec "$DAEMON" $VIRTLOGD_ARGS 2>/dev/null
