#!/bin/sh
# MySQL/MariaDB server
exec 2>&1

DAEMON="$(command -v mysqld)"
[ -x "$DAEMON" ] || exit

[ -f /etc/default/mysql ] && . /etc/default/mysql
[ -f /etc/default/mariadb ] && . /etc/default/mariadb
[ -e /var/run/mysqld ] || install -m 755 -o mysql -g root -d /var/run/mysqld
[ -d /var/log/mysql ] && chown mysql /var/log/mysql 2>/dev/null

export HOME=/etc/mysql
if [ ! -e "$HOME/my.cnf" ]; then
	printf 'ERROR: %s/my.cnf is missing.\n' "$HOME"
	exit 1
fi

DATADIR=$(grep -R '^datadir' "$HOME"/* 2>/dev/null | tail -n 1 | sed 's/.*=\s*//')
if [ ! -d "$DATADIR" ]; then
	printf 'ERROR: datadir configuration in %s is invalid.\n' "$HOME"
	exit 1
fi

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

exec chpst -u mysql "$DAEMON"
