#!/bin/sh
# Start NTP daemon
exec 2>&1

DAEMON=$(command -v ntpd)
[ -x "$DAEMON" ] || exit

# support for both ntp and ntpsec
MODE=ntp
$DAEMON --version | grep -q ntpsec && MODE=ntpsec
[ -r /etc/default/$MODE ] && . /etc/default/$MODE
[ "$IGNORE_DHCP" != "yes" ] && [ -e /run/$MODE.conf.dhcp ] && \
 NTPD_OPTS="$NTPD_OPTS -c /run/$MODE.conf.dhcp"
NTPD_OPTS="$NTPD_OPTS -n -u $MODE:$MODE"

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# kill unsupervised instance
pkill -f "$DAEMON"

exec $DAEMON $NTPD_OPTS
