#!/bin/sh
# 3Dconnexion Input Devices Userspace Driver
#
# (jan@wespe.dev)
exec 2>&1

NAME=${PWD##*/}
DAEMON="$(command -v $NAME)"
[ -x "$DAEMON" ] || exit

# ensure sysvinit compatibility - replace init.d script with symlink to sv
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# Wait for X11
sv check X11dm >/dev/null || exit

# ensure no other spacenavd is running
pkill "$NAME"

exec "$DAEMON" -d >/dev/null 2>/dev/null
