#!/bin/sh -e
# Called when a new interface comes up
# Written by LaMont Jones <lamont@debian.org>

# don't bother to restart postfix when lo is configured.
[ "$IFACE" = "lo" ] && exit

# If /usr isn't mounted yet, silently bail.
[ -d /usr/lib/postfix ] || exit

RUNNING=""
if [ -f /var/spool/postfix/pid/master.pid ]; then
	pid=$(sed 's/ //g' /var/spool/postfix/pid/master.pid)
	exe=$(ls -l /proc/$pid/exe 2>/dev/null | sed 's/.* //;s/.*\///')
	[ "$exe" = "master" ] && RUNNING="y"
fi

# start or reload Postfix as needed
if [ ! -x /sbin/resolvconf ]; then
	f=/etc/resolv.conf
	cp $f $(postconf -hx queue_directory)$f 2>/dev/null || exit
	if [ "$(pgrep runsvdir)" ]; then
		sv reload postfix >/dev/null || true
	elif [ -n "$RUNNING" ]; then
		service postfix reload >/dev/null 2>&1
	fi
fi

# If master is running, force a queue run to unload any mail that is
# hanging around.  Yes, sendmail is a symlink...
if [ "$RUNNING" ] && [ -x /usr/sbin/sendmail ]; then
	/usr/sbin/sendmail -q >/dev/null 2>&1
fi
