#!/bin/sh
# System-wide dbus
exec 2>&1

DAEMON=$(command -v dbus-daemon)
[ -x "$DAEMON" ] || exit

[ ! -d /run/dbus ] && install -m755 -d /run/dbus

# Create machine ID file
UUIDGEN=$(command -v dbus-uuidgen)
[ -x "$UUIDGEN" ] && "$UUIDGEN" --ensure

# ensure sysvinit compatibility - replace init.d script with symlink to sv
NAME=${PWD##*/}
if [ -f /etc/init.d/$NAME ] && [ ! -h /etc/init.d/$NAME ]; then
	mv -f /etc/init.d/$NAME /etc/init.d/${NAME}.sysv
	ln -sf "$(command -v sv)" /etc/init.d/$NAME
fi

# NOTE: --nosyslog might not be supported on older dbus
NOSYSLOG=$($DAEMON -h 2>&1 | grep -o ..nosyslog)

exec "$DAEMON" --system --nofork --nopidfile $NOSYSLOG >/dev/null 2>/dev/null
